"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import type { LibraryOption } from "@/lib/libraries";
type Device = {id:string;name:string;macAddress:string;libraryId:string;active:boolean;online:boolean;rssi?:number;queueDepth:number;clockReady:boolean;firmwareVersion:string;lastSeen:string};
export function DeviceManager({devices,libraries,canManage}:{devices:Device[];libraries:LibraryOption[];canManage:boolean}){
 const router=useRouter();const[busy,setBusy]=useState<string|null>(null);
 async function update(d:Device,patch:Record<string,unknown>){setBusy(d.id);const res=await fetch(`/api/admin/devices/${d.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(patch)});setBusy(null);if(!res.ok){alert("Could not update device.");return;}router.refresh();}
 return <div className="device-grid">{devices.map(d=><article className="card device-card" key={d.id}><div className="device-head"><div><h3>{d.name}</h3><div className="subtle">{d.macAddress}</div></div><span className={`badge ${d.online?"green":"red"}`}>{d.online?"ONLINE":"OFFLINE"}</span></div><div className="field" style={{marginTop:14}}><label>Assigned library</label><select className="select" value={d.libraryId} disabled={!canManage||busy===d.id} onChange={(e)=>update(d,{libraryId:e.target.value})}>{libraries.map((library)=><option key={library.id} value={library.id}>{library.name}</option>)}</select></div><div className="device-stats"><div className="mini-stat"><span>Wi-Fi RSSI</span><b>{d.rssi!=null?`${d.rssi} dBm`:"—"}</b></div><div className="mini-stat"><span>Offline queue</span><b>{d.queueDepth}</b></div><div className="mini-stat"><span>Clock</span><b>{d.clockReady?"Synced":"Not ready"}</b></div></div><div style={{marginTop:14}} className="subtle">Firmware {d.firmwareVersion||"—"} · Last heartbeat {d.lastSeen}</div>{canManage&&<div className="toolbar-actions" style={{marginTop:14}}><button className="btn" disabled={busy===d.id} onClick={()=>{const name=prompt("Reader name",d.name);if(name&&name!==d.name)update(d,{name})}}>Rename</button><button className={`btn ${d.active?"danger":""}`} disabled={busy===d.id} onClick={()=>update(d,{active:!d.active})}>{d.active?"Disable reader":"Enable reader"}</button></div>}</article>)}</div>;
}
