import { eventHistory } from "@/lib/services/dashboard";
import { allowedLibraryIds, currentAdmin } from "@/lib/auth";
import { PersonCell } from "@/components/PersonCell";
import { formatDateIST, formatIST } from "@/lib/time";
import { AutoRefresh } from "@/components/AutoRefresh";
import { librariesList, libraryName } from "@/lib/libraries";

function badge(status:string,direction?:string){if(status==="PROCESSED")return <span className={`badge ${direction==="IN"?"green":"blue"}`}>{direction}</span>;if(status==="DUPLICATE")return <span className="badge amber">DUPLICATE</span>;return <span className="badge red">{status}</span>}
export default async function EventsPage({searchParams}:{searchParams:Promise<{library?:string}>}){const sp=await searchParams;const admin=await currentAdmin();const libraries=await librariesList();const visibleLibraries=admin?.role==="SUPER_ADMIN"?libraries:libraries.filter((library)=>admin?.assignedLibraryIds.includes(library.id));const showAll=admin?.role==="SUPER_ADMIN"||visibleLibraries.length>1;const selectedLibrary=sp.library&&visibleLibraries.some((library)=>library.id===sp.library)?sp.library:(admin?.role==="SUPER_ADMIN"?"all":(visibleLibraries[0]?.id??"all"));const events:any[]=await eventHistory(admin?allowedLibraryIds(admin,selectedLibrary):[]);return <main className="page-wrap"><AutoRefresh/><div className="page-heading"><span className="eyebrow">Immutable input</span><h2>RFID scan events</h2><p>The event log is the audit source used to project visits. Device retries reuse the same event ID; duplicate physical scans remain visible without changing IN/OUT state.</p></div><section className="card table-card"><form className="toolbar" method="get"><div className="toolbar-title"><b>Latest {events.length} events</b><span>Newest network arrivals first</span></div><div className="toolbar-actions"><select className="select" name="library" defaultValue={selectedLibrary}>{showAll&&<option value="all">All Libraries</option>}{visibleLibraries.map((library)=><option key={library.id} value={library.id}>{library.name}</option>)}</select><button className="btn" type="submit">Apply</button></div></form><div className="table-scroll"><table><thead><tr><th>Student</th><th>RFID</th><th>Result</th><th>Scanned at</th><th>Received at</th><th>Library</th><th>Reader</th><th>Event ID</th></tr></thead><tbody>{events.length?events.map((e:any)=><tr key={String(e._id)}><td>{e.studentId?<PersonCell name={e.studentId.name} sub={e.studentId.enrollmentNumber}/>:<span className="subtle">Unknown</span>}</td><td>{e.rfidUid}</td><td>{badge(e.status,e.direction)}</td><td>{formatDateIST(e.scannedAt)} {formatIST(e.scannedAt,true)}</td><td>{formatIST(e.receivedAt,true)}</td><td>{libraryName(e.libraryId || e.deviceId?.libraryId)}</td><td>{e.deviceId?.name||"—"}</td><td><span className="subtle" title={e.eventId}>{e.eventId.length>24?`${e.eventId.slice(0,24)}...`:e.eventId}</span></td></tr>):<tr><td colSpan={8} className="empty">No scan events recorded yet.</td></tr>}</tbody></table></div></section></main>}
