import Link from "next/link";
import { visitHistory } from "@/lib/services/dashboard";
import { allowedLibraryIds, currentAdmin } from "@/lib/auth";
import { PersonCell } from "@/components/PersonCell";
import { formatIST, istDateKey } from "@/lib/time";
import { librariesList, libraryName } from "@/lib/libraries";

function duration(a:Date|string,b?:Date|string){if(!b)return "Open";const m=Math.max(0,Math.floor((new Date(b).getTime()-new Date(a).getTime())/60000));return m>=60?`${Math.floor(m/60)}h ${m%60}m`:`${m}m`;}

export default async function VisitsPage({searchParams}:{searchParams:Promise<{date?:string;q?:string;library?:string}>}){
 const sp=await searchParams;const admin=await currentAdmin();const libraries=await librariesList();const visibleLibraries=admin?.role==="SUPER_ADMIN"?libraries:libraries.filter((library)=>admin?.assignedLibraryIds.includes(library.id));const showAll=admin?.role==="SUPER_ADMIN"||visibleLibraries.length>1;const date=/^\d{4}-\d{2}-\d{2}$/.test(sp.date||"")?sp.date!:istDateKey(new Date());const q=sp.q||"";const selectedLibrary=sp.library&&visibleLibraries.some((library)=>library.id===sp.library)?sp.library:(admin?.role==="SUPER_ADMIN"?"all":(visibleLibraries[0]?.id??"all"));const dateObj=new Date(`${date}T12:00:00+05:30`);const rows:any[]=await visitHistory(dateObj,q,admin?allowedLibraryIds(admin,selectedLibrary):[]);
 return <main className="page-wrap"><div className="page-heading"><span className="eyebrow">Audit register</span><h2>Visit history</h2><p>Each row represents one library visit with its original IN timestamp, OUT timestamp and closure method.</p></div>
 <section className="card table-card"><form className="toolbar" method="get"><div className="toolbar-title"><b>{rows.length} visits</b><span>Selected operating day and library scope</span></div><div className="toolbar-actions"><select className="select" name="library" defaultValue={selectedLibrary}>{showAll&&<option value="all">All Libraries</option>}{visibleLibraries.map((library)=><option key={library.id} value={library.id}>{library.name}</option>)}</select><input className="input" style={{width:150}} type="date" name="date" defaultValue={date}/><input className="input search" name="q" defaultValue={q} placeholder="Search student, RFID..."/><button className="btn" type="submit">Apply</button><Link className="btn primary" href={`/api/admin/visits/export?date=${encodeURIComponent(date)}&library=${encodeURIComponent(selectedLibrary)}`}>Export CSV</Link></div></form><div className="table-scroll"><table><thead><tr><th>Student</th><th>Library</th><th>IN</th><th>OUT</th><th>Duration</th><th>Exit method</th><th>Readers</th></tr></thead><tbody>{rows.length?rows.map((v:any)=>{const s=v.studentId;return <tr key={String(v._id)}><td><PersonCell name={s?.name||"Unknown"} sub={`${s?.enrollmentNumber||""}${s?.course?` · ${s.course}`:""}`}/></td><td>{libraryName(v.inLibraryId || v.inDeviceId?.libraryId)}</td><td>{formatIST(v.inAt,true)}</td><td>{v.outAt?formatIST(v.outAt,true):"—"}</td><td>{duration(v.inAt,v.outAt)}</td><td>{v.outMethod==="AUTO_6PM"?<span className="badge amber">AUTO 6 PM</span>:v.outMethod==="RFID_SCAN"?<span className="badge blue">RFID SCAN</span>:<span className="badge green">OPEN</span>}</td><td><span className="subtle">{v.inDeviceId?.name||"—"}{v.outDeviceId?` → ${v.outDeviceId.name}`:""}</span></td></tr>}):<tr><td className="empty" colSpan={7}>No visits found for this date.</td></tr>}</tbody></table></div></section></main>;
}
